"""Bohemian Marketing Service API blueprint.

This module provides the orchestration surface for the new all-in-one marketing
project and is intentionally lightweight so agent teams can extend each domain
without waiting on shared state.
"""
from __future__ import annotations

from datetime import datetime
from threading import Lock
from flask import Blueprint, request, jsonify

bohemian_marketing_bp = Blueprint("bohemian_marketing", __name__, url_prefix="/api/bohemian-marketing")


_state = {
    "brands": [],
    "personas": [],
    "content": [],
    "schedules": [],
    "inbox": [],
    "autopilot": {
        "enabled": False,
        "daily_limit": 3,
        "channel_caps": {"threads": 3, "x": 3},
        "terms_accepted": False,
    },
}

_lock = Lock()


def _next_id(items):
    return (max((i.get("id", 0) for i in items), default=0) + 1)


@bohemian_marketing_bp.route("", methods=["GET"])
def ping():
    """Service health and capability list."""
    return jsonify({
        "service": "bohemian-marketing",
        "status": "ready",
        "modules": ["persona", "studio", "autopilot", "inbox", "analytics", "billing"]
    }), 200


@bohemian_marketing_bp.route("/brands", methods=["GET", "POST"])
def brands():
    if request.method == "GET":
        return jsonify(_state["brands"]), 200

    payload = request.get_json(silent=True) or {}
    required = ("name", "industry", "target_audience")
    if not all(payload.get(f) for f in required):
        return jsonify({"error": "name, industry, target_audience are required"}), 400

    with _lock:
        brand = {
            "id": _next_id(_state["brands"]),
            "name": payload["name"],
            "industry": payload["industry"],
            "target_audience": payload["target_audience"],
            "tone_rules_json": payload.get("tone_rules_json", {}),
            "banned_words_json": payload.get("banned_words_json", []),
            "created_at": datetime.utcnow().isoformat() + "Z",
        }
        _state["brands"].append(brand)

    return jsonify(brand), 201


@bohemian_marketing_bp.route("/personas", methods=["GET", "POST"])
def personas():
    if request.method == "GET":
        return jsonify(_state["personas"]), 200

    payload = request.get_json(silent=True) or {}
    brand_id = payload.get("brand_id")
    prompt_pack = payload.get("prompt_pack_json", {})
    if not brand_id:
        return jsonify({"error": "brand_id is required"}), 400

    with _lock:
        persona = {
            "id": _next_id(_state["personas"]),
            "brand_id": brand_id,
            "version": payload.get("version", "v1"),
            "profile_json": payload.get("profile_json", {}),
            "prompt_pack_json": prompt_pack,
            "created_at": datetime.utcnow().isoformat() + "Z",
        }
        _state["personas"].append(persona)

    return jsonify(persona), 201


@bohemian_marketing_bp.route("/content", methods=["POST"])
def generate_content():
    """Create multi-format content package from a single topic."""
    payload = request.get_json(silent=True) or {}
    topic = payload.get("topic", "").strip()
    if not topic:
        return jsonify({"error": "topic is required"}), 400

    brand_id = payload.get("brand_id")
    with _lock:
        item = {
            "id": _next_id(_state["content"]),
            "brand_id": brand_id,
            "topic": topic,
            "goal": payload.get("goal", "awareness"),
            "formats": {
                "threads": f"{topic} — thread draft generated by persona pack.",
                "x": f"{topic} — X post draft generated by persona pack.",
                "blog": f"{topic}\n\n## Core message\n\nAutopilot-ready long form draft.",
                "card_news": {
                    "slides": 6,
                    "headline": topic,
                    "call_to_action": payload.get("cta", "Learn more")
                },
            },
            "status": "draft",
            "created_at": datetime.utcnow().isoformat() + "Z",
        }
        _state["content"].append(item)

    return jsonify(item), 201


@bohemian_marketing_bp.route("/schedules", methods=["POST"])
def create_schedule():
    payload = request.get_json(silent=True) or {}
    content_id = payload.get("content_id")
    if not content_id:
        return jsonify({"error": "content_id is required"}), 400

    item = next((c for c in _state["content"] if c["id"] == content_id), None)
    if not item:
        return jsonify({"error": "content item not found"}), 404

    schedule = {
        "id": _next_id(_state["schedules"]),
        "content_id": content_id,
        "channel": payload.get("channel", "threads"),
        "scheduled_at": payload.get("scheduled_at", datetime.utcnow().isoformat() + "Z"),
        "status": "queued",
        "created_at": datetime.utcnow().isoformat() + "Z",
    }
    _state["schedules"].append(schedule)
    return jsonify(schedule), 201


@bohemian_marketing_bp.route("/inbox/threads", methods=["GET", "POST"])
def inbox_threads():
    if request.method == "GET":
        return jsonify(_state["inbox"]), 200

    payload = request.get_json(silent=True) or {}
    if not payload.get("content"):
        return jsonify({"error": "content is required"}), 400

    thread = {
        "id": _next_id(_state["inbox"]),
        "type": payload.get("type", "comment"),
        "platform": payload.get("platform", "threads"),
        "content": payload["content"],
        "status": payload.get("status", "open"),
        "created_at": datetime.utcnow().isoformat() + "Z",
        "messages": [],
    }
    _state["inbox"].append(thread)
    return jsonify(thread), 201


@bohemian_marketing_bp.route("/autopilot", methods=["GET", "POST"])
def autopilot():
    if request.method == "GET":
        return jsonify(_state["autopilot"]), 200

    payload = request.get_json(silent=True) or {}
    action = payload.get("action")
    if action == "enable":
        if not payload.get("terms_accepted"):
            return jsonify({"error": "terms_accepted is required"}), 400
        _state["autopilot"]["enabled"] = True
        _state["autopilot"]["terms_accepted"] = True
        _state["autopilot"]["daily_limit"] = payload.get("daily_limit", 3)
    elif action == "disable":
        _state["autopilot"]["enabled"] = False
    else:
        return jsonify({"error": "action must be enable or disable"}), 400

    return jsonify(_state["autopilot"]), 200


@bohemian_marketing_bp.route("/analytics/overview", methods=["GET"])
def analytics_overview():
    return jsonify({
        "service": "bohemian-marketing",
        "kpi": {
            "contents_draft": len(_state["content"]),
            "schedules_total": len(_state["schedules"]),
            "inbox_open": len([i for i in _state["inbox"] if i.get("status") == "open"]),
            "autopilot_enabled": _state["autopilot"]["enabled"],
        }
    }), 200


@bohemian_marketing_bp.route("/content/<int:content_id>/publish-wordpress", methods=["POST"])
def publish_content_to_wordpress(content_id):
    """
    Publish a content item's blog draft directly to WordPress.

    Request body (JSON):
        site_url    : str  — WordPress site (e.g. "https://myblog.com")
        wp_username : str  — WordPress username
        access_token: str  — Application Password
        status      : str  — 'publish' | 'draft' (default: 'publish')
        categories  : list — optional WordPress category IDs
        hashtags    : list — optional hashtag strings (converted to WP tags)

    Returns:
        {success, url, external_post_id, status}
    """
    item = next((c for c in _state["content"] if c["id"] == content_id), None)
    if not item:
        return jsonify({"error": "content item not found"}), 404

    blog_draft = item.get("formats", {}).get("blog", "")
    if not blog_draft:
        return jsonify({"error": "No blog format available for this content item"}), 400

    payload = request.get_json(silent=True) or {}
    site_url = (payload.get("site_url") or "").strip().rstrip("/")
    wp_username = (payload.get("wp_username") or "").strip()
    access_token = (payload.get("access_token") or "").strip()
    pub_status = payload.get("status", "publish")

    if not site_url or not wp_username or not access_token:
        return jsonify({"error": "site_url, wp_username, and access_token are required"}), 400

    try:
        from .sns_platforms import get_client as get_platform_client
        client = get_platform_client(
            "wordpress",
            access_token=access_token,
            simulation_mode=False,
            site_url=site_url,
            wp_username=wp_username,
        )

        result = client.post_content(
            content=blog_draft,
            title=item.get("topic", ""),
            hashtags=payload.get("hashtags", []),
            categories=payload.get("categories"),
            status=pub_status,
        )

        if result.get("success"):
            # Mark content item as published
            with _lock:
                item["status"] = "published"
                item["published_url"] = result.get("url", "")
                item["external_post_id"] = result.get("external_post_id", "")

        return jsonify(result), 200 if result.get("success") else 502

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500

